// routes/pdf.js — Backend PDF generation with Unicode support
// Uses PDFKit which supports any language text properly

const express = require("express");
const router = express.Router();
const PDFDocument = require("pdfkit");

/**
 * POST /api/pdf
 * Body: { summary: string, videoUrl: string, videoId: string }
 * Returns: PDF file stream
 */
router.post("/", (req, res) => {
  const { summary, videoUrl, videoId } = req.body;

  if (!summary) {
    return res.status(400).json({ error: "No summary provided." });
  }

  // Create PDF document
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 50, bottom: 50, left: 60, right: 60 },
    info: {
      Title: "Video Summary — SUMMARIZER",
      Author: "SUMMARIZER AI",
      Subject: videoUrl || "",
    },
  });

  // Set response headers so browser downloads it as a PDF
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="summary-${videoId || "video"}.pdf"`);

  // Pipe PDF directly to response
  doc.pipe(res);

  const pageWidth = doc.page.width - 120; // usable width

  // ── Header bar ─────────────────────────────────────────────
  doc.rect(0, 0, doc.page.width, 8).fill("#2563eb");

  // ── Title ──────────────────────────────────────────────────
  doc.moveDown(1.5);
  doc.fontSize(22).fillColor("#0f172a").font("Helvetica-Bold").text("Video Summary", { align: "left" });

  doc.moveDown(0.3);
  doc.fontSize(11).fillColor("#2563eb").font("Helvetica-Bold").text("SUMMARIZER", { align: "left" });

  // ── Divider ────────────────────────────────────────────────
  doc.moveDown(0.8);
  doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#e2e8f0").lineWidth(1).stroke();
  doc.moveDown(0.8);

  // ── Metadata ───────────────────────────────────────────────
  if (videoUrl) {
    doc.fontSize(9).fillColor("#94a3b8").font("Helvetica").text(`Source: ${videoUrl}`, { width: pageWidth });
  }
  doc.fontSize(9).fillColor("#94a3b8").font("Helvetica")
    .text(`Generated: ${new Date().toLocaleString("en-IN", { dateStyle: "long", timeStyle: "short" })}`, { width: pageWidth });

  doc.moveDown(1.2);

  // ── Summary content ────────────────────────────────────────
  // Parse and render each line with proper styling
  const lines = summary.split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) { doc.moveDown(0.4); continue; }

    if (line.startsWith("## ")) {
      // Section heading
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor("#2563eb").font("Helvetica-Bold")
        .text(line.replace("## ", "").toUpperCase(), { width: pageWidth });
      doc.moveDown(0.4);

    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      // Bullet point — render bullet + text
      const bulletText = line.replace(/^[-•]\s*/, "");
      const currentY = doc.y;
      doc.fontSize(11).fillColor("#1e293b").font("Helvetica")
        .text("•", 60, currentY, { width: 15, continued: false });
      doc.text(bulletText, 78, currentY, { width: pageWidth - 18 });
      doc.moveDown(0.2);

    } else if (/^\d+\./.test(line)) {
      // Numbered list
      const num = line.match(/^(\d+)\./)[1];
      const text = line.replace(/^\d+\.\s*/, "");
      const currentY = doc.y;
      doc.fontSize(11).fillColor("#2563eb").font("Helvetica-Bold")
        .text(`${num}.`, 60, currentY, { width: 20 });
      doc.fontSize(11).fillColor("#1e293b").font("Helvetica")
        .text(text, 82, currentY, { width: pageWidth - 22 });
      doc.moveDown(0.3);

    } else {
      // Regular paragraph
      doc.fontSize(11).fillColor("#334155").font("Helvetica")
        .text(line, { width: pageWidth, lineGap: 3 });
      doc.moveDown(0.4);
    }

    // New page if near bottom
    if (doc.y > doc.page.height - 80) {
      doc.addPage();
      doc.rect(0, 0, doc.page.width, 8).fill("#2563eb");
      doc.moveDown(2);
    }
  }

  // ── Footer ─────────────────────────────────────────────────
  doc.moveDown(2);
  doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#e2e8f0").lineWidth(1).stroke();
  doc.moveDown(0.5);
  doc.fontSize(9).fillColor("#94a3b8").font("Helvetica")
    .text("Generated by SUMMARIZER · AI-powered YouTube Video Summarizer", { align: "center" });

  doc.end();
});

module.exports = router;
